# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - right_lara8_controller
    - left_lara8_controller

  right_lara8_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_lara8_joint1
      - right_lara8_joint2
      - right_lara8_joint3
      - right_lara8_joint4
      - right_lara8_joint5
      - right_lara8_joint6

  left_lara8_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_lara8_joint1
      - left_lara8_joint2
      - left_lara8_joint3
      - left_lara8_joint4
      - left_lara8_joint5
      - left_lara8_joint6

  