# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    right_lara8_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_lara8_controller:
      type: joint_trajectory_controller/JointTrajectoryController

right_lara8_controller:
  ros__parameters:
    joints:
      - right_lara8_joint1
      - right_lara8_joint2
      - right_lara8_joint3
      - right_lara8_joint4
      - right_lara8_joint5
      - right_lara8_joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    
   
      
left_lara8_controller:
  ros__parameters:
    joints:
      - left_lara8_joint1
      - left_lara8_joint2
      - left_lara8_joint3
      - left_lara8_joint4
      - left_lara8_joint5
      - left_lara8_joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    

